# Makefile for CH32C203x8
# 09-16-2023 E. Brombaugh

# sub directories
VPATH = .:../Peripheral/src:../Core:../Startup

# Object files
OBJECTS =   startup_ch32v20x_D8.o core_riscv.o main.o debug.o \
			system_ch32v20x.o ch32v20x_it.o ch32v20x_misc.o \
			ch32v20x_pwr.o ch32v20x_rcc.o ch32v20x_gpio.o ch32v20x_usart.o
			
include ../misc/makefile.mk

